name: Prevent Direct Push

on:
  push:
    branches:
      - main
      - deploy

jobs:
  prevent-push:
    runs-on: ubuntu-latest
    steps:
      - name: Stop direct pushes
        run: |
          echo "🚫 Direct pushes to main or deploy are blocked."
          exit 1
